### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by acpn** [llSourcell/build_a_neural_net_live#4]
Hi Siraj, I'm work with caffe and c++ and i`ll trying to change to tensorflow and python, I'm following this tutorial your and i've this problem when i'm running the code:

`Vectorizing text...
Text total length: 207041
Distinct chars: 61
## Total sequences: 69007

Run id: us cities
Log directory: /tmp/tflearn_logs/
Traceback (most recent call last):
  File "lstm_by_tutorial.py", line 39, in <module>
    n_epoch=1, run_id='us cities')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/generator.py", line 174, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 247, in fit
    max_batches_len = np.max([t.n_batches for t in self.train_ops])
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2293, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
`

I don't know if is a python bug or some dependencies is lost, i realy apreciate if you can have any idea.

Thanks and keep going with you really good job.

**Comment by acpn** [comment]
I fix that, some dependencies they were not installed.

**Comment by spatel95** [comment]
Hey acpn, can you tell me the dependencies? I have the same exact error
